name: CD

on:
  workflow_dispatch:
    inputs:
      update-tag:
        description: "input yes means bump up tag version, and no means update the tag to top"
        required: true
        default: "no"
jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Validate CD branch
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/release' && github.ref != 'refs/heads/main' }}
        run: |
          echo It's not allowed to run CD on other branch except release.
          exit 1
      
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: fetch latest tag
        uses: actions-ecosystem/action-get-latest-tag@b7c32daec3395a9616f88548363a42652b22d435 # v1.6.0
        id: get-latest-tag
      
      - name: update tag
        uses: richardsimko/update-tag@aab2434e9a5040687874aa39d1c6377ec0cb0d94 # v1.1.6
        if: ${{ github.event.inputs.update-tag == 'no' }}
        with:
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        if: ${{ github.event.inputs.update-tag != 'no' }}
        uses: anothrNick/github-tag-action@9aaabdb5e989894e95288328d8b17a6347217ae3 # 1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: ${{ steps.get-latest-tag.outputs.tag }}
          RELEASE_BRANCHES: "main"
